%%
%% Autogenerated by Thrift
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%


-include("xleThriftService_types.hrl").

-define(xleThriftService_DEFAULT_DETAILS, dict:from_list([("kind","xle"),("grammar","query")])).

